import "server-only";

import { createHash, timingSafeEqual } from "node:crypto";

import { supabaseAdmin } from "@/lib/supabase/server";

const MAX_TOKEN_BYTES = 512;

export type CronAuthorization =
  | { ok: true }
  | { ok: false; status: 401 | 503; message: "Unauthorized" | "Authorization unavailable" };

/**
 * Authenticate either Vercel Cron or the Vault-backed Supabase scheduler.
 *
 * The database stores only a SHA-256 digest of the scheduler token. The
 * plaintext lives in Vault and is presented over TLS as a bearer token.
 */
export async function authorizeCronRequest(
  request: Pick<Request, "headers">,
): Promise<CronAuthorization> {
  const token = bearerToken(request.headers.get("authorization"));
  if (!token) return { ok: false, status: 401, message: "Unauthorized" };

  const configured = process.env.CRON_SECRET;
  if (configured && secretsEqual(token, configured)) return { ok: true };

  // Vault tokens are generated by us and must have meaningful entropy. Keep
  // accepting an older, shorter CRON_SECRET exactly so this rollout cannot
  // accidentally lock Vercel out before that secret is rotated.
  if (Buffer.byteLength(token, "utf8") < 32) {
    return { ok: false, status: 401, message: "Unauthorized" };
  }

  try {
    const digest = createHash("sha256").update(token, "utf8").digest("hex");
    const { data, error } = await supabaseAdmin().rpc(
      "verify_notification_scheduler_token",
      { p_token_sha256: digest },
    );
    if (error) {
      console.error("Cron scheduler authorization lookup failed");
      return { ok: false, status: 503, message: "Authorization unavailable" };
    }
    return data === true
      ? { ok: true }
      : { ok: false, status: 401, message: "Unauthorized" };
  } catch {
    console.error("Cron scheduler authorization lookup threw");
    return { ok: false, status: 503, message: "Authorization unavailable" };
  }
}

function bearerToken(header: string | null): string | null {
  if (!header?.startsWith("Bearer ")) return null;
  const token = header.slice("Bearer ".length);
  const size = Buffer.byteLength(token, "utf8");
  return token.trim() === token && size > 0 && size <= MAX_TOKEN_BYTES
    ? token
    : null;
}

function secretsEqual(candidate: string, expected: string): boolean {
  const candidateHash = createHash("sha256").update(candidate, "utf8").digest();
  const expectedHash = createHash("sha256").update(expected, "utf8").digest();
  return timingSafeEqual(candidateHash, expectedHash);
}
