-- Minimum Stress — full schema, generated from supabase/migrations/
--
-- Generated by scripts/build-apply-sql.mjs — edit the migrations, not this.
--
-- Safe to run more than once. Every statement is guarded, so pasting this
-- into a project that already has some of it is boring rather than a
-- transaction that aborts halfway and leaves you guessing what landed.
--
-- 0000_supabase_stubs.sql is deliberately NOT included: it recreates what
-- Supabase already provides and exists only so the test suite can run the
-- migrations against a bare Postgres.

-- ===================================================================
-- 0001_schema.sql
-- ===================================================================

-- Minimum Stress — core schema
--
-- Not yet applied to a live project. Written against the data model in the
-- Phase 1 plan; run `supabase db push` (or paste into the SQL editor) once
-- Supabase keys are available, then read it back with `supabase db diff` to
-- confirm nothing drifted before trusting it in production.
--
-- Money columns mirror src/lib/money.ts's BookingMoney type field-for-field,
-- because a booking freezes the quote that produced it — a host raising their
-- rate later must never rewrite what a past booking cost.

-- No pgcrypto extension: gen_random_uuid() has been core Postgres since 13 and
-- Supabase runs 15+, so requiring the extension would only narrow where these
-- migrations can run.

-- Every statement in this file is safe to re-run. Postgres has no
-- `create type if not exists`, hence the wrapper; tables and indexes use the
-- built-in guard.
--
-- This matters more than it looks. Applying the full script to a project that
-- already has most of it should be boring, not a transaction that aborts on
-- line 16 and leaves the reader guessing which half landed.
do $$ begin
  create type space_category as enum ('physical', 'traditional', 'social', 'spirit');
exception when duplicate_object then null; end $$;

do $$ begin
  create type access_type as enum ('keypad', 'lockbox', 'greeter');
exception when duplicate_object then null; end $$;

do $$ begin
  create type restroom_option as enum ('private', 'shared', 'none');
exception when duplicate_object then null; end $$;

do $$ begin
  create type space_status as enum ('pending', 'active', 'delisted');
exception when duplicate_object then null; end $$;

do $$ begin
  create type media_kind as enum ('image', 'video');
exception when duplicate_object then null; end $$;

do $$ begin
  create type payout_schedule as enum ('standard', 'instant');
exception when duplicate_object then null; end $$;

do $$ begin
  create type booking_status as enum (
    'upcoming', 'completed', 'cancelled_by_practitioner', 'cancelled_by_host', 'no_show'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type cancelled_by_actor as enum ('practitioner', 'host');
exception when duplicate_object then null; end $$;

do $$ begin
  create type credit_reason as enum ('host_cancellation', 'booking_redemption', 'goodwill_restore');
exception when duplicate_object then null; end $$;

-- ------------------------------------------------------------------
-- profiles
--
-- One row per auth.users row. No "role" column: the brief's Role Select
-- screen ("You can switch anytime from the top of either screen") is a UI
-- entry point, not a database-enforced identity — the same person can host a
-- space and book someone else's on the same account.
-- ------------------------------------------------------------------
create table if not exists profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  avatar_path text,
  is_pro boolean not null default false,
  pro_since timestamptz,
  stripe_customer_id text unique,
  stripe_connect_account_id text unique,
  stripe_connect_charges_enabled boolean not null default false,
  insurance_doc_path text,
  payout_schedule payout_schedule not null default 'standard',
  notify_bookings boolean not null default true,
  notify_payouts boolean not null default true,
  notify_offers boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------------
-- spaces
--
-- room_type is not stored: it is a pure function of category
-- (lib/taxonomy.ts roomTypeFor), so there is exactly one place the two can
-- ever disagree — the lookup table — rather than a column that can drift
-- from it.
--
-- address_line / lat / lng / entry_instructions are private until a
-- practitioner has a confirmed booking on this space. See 0002_rls.sql for
-- how that boundary is actually enforced — column *visibility* rather than
-- a client-side check, so the private fields never leave the server for an
-- unauthorized request in the first place.
-- ------------------------------------------------------------------
create table if not exists spaces (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references profiles (id) on delete cascade,
  name text not null,
  category space_category not null,
  hourly_rate_cents integer not null check (hourly_rate_cents > 0),
  capacity integer not null check (capacity > 0),
  access_type access_type not null,
  entry_instructions text not null,
  address_line text not null,
  lat double precision,
  lng double precision,
  accessible boolean,
  restroom restroom_option,
  buffer_minutes integer not null default 0 check (buffer_minutes >= 0),
  status space_status not null default 'pending',
  sublease_doc_path text not null,
  insurance_doc_path text,
  legal_ack_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists spaces_host_id_idx on spaces (host_id);
create index if not exists spaces_status_idx on spaces (status) where status = 'active';

-- ------------------------------------------------------------------
-- space_media
--
-- The brief requires at least one photo or video per listing but never
-- gates step 1 or 2 on anything past that, so this table has no NOT NULL
-- constraint tying it to a minimum count — that rule lives in application
-- validation at submission time, where it can produce a helpful error
-- instead of a database exception.
-- ------------------------------------------------------------------
create table if not exists space_media (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references spaces (id) on delete cascade,
  storage_path text not null,
  kind media_kind not null,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists space_media_space_id_idx on space_media (space_id, position);

-- ------------------------------------------------------------------
-- availability
--
-- One row per block, not one row per day. This is what lets a single Monday
-- hold 7-8am, 2-3pm and 5-9pm as three independent rows rather than forcing
-- one start/end pair per weekday.
-- ------------------------------------------------------------------
create table if not exists availability (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references spaces (id) on delete cascade,
  weekday smallint not null check (weekday between 0 and 6),
  start_minute smallint not null check (start_minute between 0 and 1439),
  end_minute smallint not null check (end_minute between 1 and 1440),
  constraint availability_ordered check (end_minute > start_minute)
);

create index if not exists availability_space_id_idx on availability (space_id, weekday);

-- ------------------------------------------------------------------
-- bookings
--
-- Every money column is frozen at creation from a src/lib/money.ts Quote —
-- never recomputed from the space's current rate. access_code is generated
-- but withheld from API responses until access_code_revealed_at (target:
-- T-30min), enforced server-side, not by hiding it in the client.
-- ------------------------------------------------------------------
-- on delete restrict, deliberately: a booking is a financial record tied to a
-- Stripe PaymentIntent and possibly a credit_ledger entry. Cascading a space
-- or profile deletion into it would silently destroy the audit trail for money
-- that actually moved. Deleting either has to reckon with its bookings first.
create table if not exists bookings (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references spaces (id) on delete restrict,
  practitioner_id uuid not null references profiles (id) on delete restrict,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status booking_status not null default 'upcoming',
  is_instant boolean not null,
  was_pro boolean not null,

  -- Frozen quote — see src/lib/money.ts BookingMoney.
  host_rate_cents integer not null,
  service_fee_cents integer not null,
  instant_fee_cents integer not null,
  pro_discount_cents integer not null,
  credit_applied_cents integer not null,
  total_cents integer not null,
  platform_cents integer not null,

  stripe_payment_intent_id text unique,
  authorized_at timestamptz,
  captured_at timestamptz,

  cancelled_at timestamptz,
  cancelled_by cancelled_by_actor,

  access_code text,
  access_code_revealed_at timestamptz,

  created_at timestamptz not null default now(),

  constraint bookings_ordered check (ends_at > starts_at),
  constraint bookings_cancellation_consistent check (
    (cancelled_at is null) = (cancelled_by is null)
  )
);

create index if not exists bookings_practitioner_id_idx on bookings (practitioner_id);
create index if not exists bookings_space_id_idx on bookings (space_id);
create index if not exists bookings_starts_at_idx on bookings (starts_at) where status = 'upcoming';

-- ------------------------------------------------------------------
-- credit_ledger
--
-- Append-only. The balance is never a stored number — it is always
-- SUM(delta_cents), matching lib/money.ts's creditBalance(). A mutable
-- balance column next to this table would be exactly the bug the prototype
-- had, where credits.balance and credits.ledger could drift apart.
-- ------------------------------------------------------------------
create table if not exists credit_ledger (
  id uuid primary key default gen_random_uuid(),
  practitioner_id uuid not null references profiles (id) on delete restrict,
  delta_cents integer not null,
  reason credit_reason not null,
  booking_id uuid references bookings (id) on delete restrict,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists credit_ledger_practitioner_id_idx on credit_ledger (practitioner_id);

-- security_invoker is load-bearing here, not decoration: without it this
-- view runs as its owner (typically the migration role) and RLS on
-- credit_ledger never applies, so every practitioner's balance becomes
-- readable by anyone granted select on the view. With it, the view enforces
-- exactly the same row policies the base table does for the querying user.
create or replace view credit_balances
  with (security_invoker = true) as
  select practitioner_id, coalesce(sum(delta_cents), 0)::integer as balance_cents
  from credit_ledger
  group by practitioner_id;


-- ===================================================================
-- 0002_rls.sql
-- ===================================================================

-- Row Level Security
--
-- Two settings from the brief stay exactly as configured and this migration
-- does not touch them: RLS is enabled project-wide, and auto-expose-new-tables
-- stays off, so a table only becomes reachable once deliberately granted here.
--
-- The organising rule, because getting this wrong is how address_line leaks:
--
--   Base tables are owner-only. authenticated may reach its own rows;
--     anon may not reach them at all.
--   Anything public goes through a security *definer* view, whose safety comes
--     from its explicit column list and WHERE clause rather than from RLS.
--   Anything per-user goes through a security *invoker* view, so the caller's
--     own row policies still apply.
--
-- The distinction is load-bearing. An invoker view over a table the caller has
-- no grant on simply errors, so "public subset" views cannot be invoker; and a
-- definer view over per-user data bypasses RLS and would hand every
-- practitioner's balance to whoever asked, so per-user views cannot be definer.
--
-- Writes to bookings and credit_ledger happen server-side under the service
-- role, never from the client: a cancellation has to void or capture a Stripe
-- PaymentIntent and write a ledger row in one transaction, and RLS can gate who
-- writes a row but cannot make that write atomic with an external API call.

-- `create policy` has no IF NOT EXISTS, so re-running this file would abort on
-- the first one that already existed. Clearing them first makes the file
-- declarative: what follows is the complete set, and applying it twice is
-- boring rather than a half-applied transaction.
--
-- Scoped to this app's own tables by name, so it cannot reach anything
-- Supabase manages.
do $$
declare existing record;
begin
  for existing in
    select policyname, tablename from pg_policies
    where schemaname = 'public'
      and tablename in (
        'profiles', 'spaces', 'space_media', 'availability', 'bookings', 'credit_ledger'
      )
  loop
    execute format('drop policy if exists %I on public.%I', existing.policyname, existing.tablename);
  end loop;
end $$;

alter table profiles enable row level security;
alter table spaces enable row level security;
alter table space_media enable row level security;
alter table availability enable row level security;
alter table bookings enable row level security;
alter table credit_ledger enable row level security;

-- ------------------------------------------------------------------
-- Table privileges
--
-- Not redundant with the policies below: a policy narrows which rows a role
-- may touch, a GRANT decides whether it may touch the table at all. With
-- auto-expose off there are no defaults, so a policy without a matching grant
-- is dead code — the role is refused before RLS is ever consulted.
-- ------------------------------------------------------------------

grant select, insert, update on profiles to authenticated;
grant select, insert, update, delete on spaces to authenticated;
grant select, insert, update, delete on space_media to authenticated;
grant select, insert, update, delete on availability to authenticated;
grant select on bookings to authenticated;
grant select on credit_ledger to authenticated;

-- ------------------------------------------------------------------
-- profiles
-- ------------------------------------------------------------------

create policy "profiles: read own row"
  on profiles for select
  using (id = auth.uid());

create policy "profiles: insert own row"
  on profiles for insert
  with check (id = auth.uid());

create policy "profiles: update own row"
  on profiles for update
  using (id = auth.uid())
  with check (id = auth.uid());

-- ------------------------------------------------------------------
-- spaces — host-only at the table. Practitioners never select from it
-- directly; they read spaces_public, and the private fields come from
-- space_access_details() once they hold a booking.
-- ------------------------------------------------------------------

create policy "spaces: host reads own rows, any status"
  on spaces for select
  using (host_id = auth.uid());

create policy "spaces: host inserts own rows"
  on spaces for insert
  with check (host_id = auth.uid());

create policy "spaces: host updates own rows"
  on spaces for update
  using (host_id = auth.uid())
  with check (host_id = auth.uid());

create policy "spaces: host deletes own rows"
  on spaces for delete
  using (host_id = auth.uid());

-- ------------------------------------------------------------------
-- space_media / availability — host-only at the table, same as spaces.
-- Public reads go through the *_public views further down.
-- ------------------------------------------------------------------

create policy "space_media: host manages own space's media"
  on space_media for all
  using (exists (select 1 from spaces s where s.id = space_id and s.host_id = auth.uid()))
  with check (exists (select 1 from spaces s where s.id = space_id and s.host_id = auth.uid()));

create policy "availability: host manages own space's schedule"
  on availability for all
  using (exists (select 1 from spaces s where s.id = space_id and s.host_id = auth.uid()))
  with check (exists (select 1 from spaces s where s.id = space_id and s.host_id = auth.uid()));

-- ------------------------------------------------------------------
-- bookings / credit_ledger — read-only for the parties involved.
-- ------------------------------------------------------------------

create policy "bookings: practitioner reads own bookings"
  on bookings for select
  using (practitioner_id = auth.uid());

create policy "bookings: host reads bookings on own spaces"
  on bookings for select
  using (exists (select 1 from spaces s where s.id = space_id and s.host_id = auth.uid()));

create policy "credit_ledger: practitioner reads own entries"
  on credit_ledger for select
  using (practitioner_id = auth.uid());

-- ==================================================================
-- Public views — security DEFINER (the default).
--
-- Safety here is structural: the column list decides what exists at all, so
-- address_line, the Stripe identifiers and the document paths are not
-- omitted-but-reachable, they are absent. A future policy change cannot
-- widen them back into view.
-- ==================================================================

-- Dropped first, not just replaced. `create or replace view` can add columns
-- but never remove them, so on a re-run this file would collide with the wider
-- definition a later migration left behind and abort the whole script.
drop view if exists spaces_public;
drop view if exists public_host_profiles;
drop view if exists availability_public;
drop view if exists space_media_public;
drop view if exists credit_balances;
drop view if exists bookings_with_access_code;

create or replace view spaces_public as
  select
    id, host_id, name, category, hourly_rate_cents, capacity, access_type,
    accessible, restroom, buffer_minutes, status, created_at
  from spaces
  where status = 'active';

grant select on spaces_public to anon, authenticated;

create or replace view public_host_profiles as
  select id, display_name, avatar_path
  from profiles;

grant select on public_host_profiles to anon, authenticated;

create or replace view availability_public as
  select a.id, a.space_id, a.weekday, a.start_minute, a.end_minute
  from availability a
  join spaces s on s.id = a.space_id
  where s.status = 'active';

grant select on availability_public to anon, authenticated;

create or replace view space_media_public as
  select m.id, m.space_id, m.storage_path, m.kind, m.position
  from space_media m
  join spaces s on s.id = m.space_id
  where s.status = 'active';

grant select on space_media_public to anon, authenticated;

-- ==================================================================
-- Per-user views — security INVOKER, so the caller's row policies apply.
-- ==================================================================

-- Without security_invoker this aggregate would sum the entire ledger and
-- hand every practitioner's balance to whoever queried it.
create or replace view credit_balances
  with (security_invoker = true) as
  select practitioner_id, coalesce(sum(delta_cents), 0)::integer as balance_cents
  from credit_ledger
  group by practitioner_id;

grant select on credit_balances to authenticated;

-- access_code itself is never selected here. The reveal is a server-side
-- timer flipping access_code_revealed_at; the raw value must not round-trip
-- to a client that is not yet entitled to it, even into a field the UI
-- happens not to render.
create or replace view bookings_with_access_code
  with (security_invoker = true) as
  select
    b.id, b.space_id, b.practitioner_id, b.starts_at, b.ends_at, b.status,
    b.is_instant, b.was_pro, b.host_rate_cents, b.service_fee_cents,
    b.instant_fee_cents, b.pro_discount_cents, b.credit_applied_cents,
    b.total_cents, b.platform_cents, b.captured_at, b.cancelled_at,
    b.cancelled_by, b.access_code_revealed_at, b.created_at,
    case
      when b.practitioner_id = auth.uid() and b.access_code_revealed_at <= now()
        then b.access_code
      else null
    end as revealed_access_code
  from bookings b;

grant select on bookings_with_access_code to authenticated;

-- ==================================================================
-- Address reveal — a security definer function, not a view.
--
-- A practitioner has no row policy on `spaces`, so an invoker view would
-- return nothing to exactly the person entitled to the address. Granting
-- them a row policy instead would expose every other column on the row,
-- including the host's sublease document path. A definer function is the
-- narrow instrument: it runs the ownership check itself and returns only the
-- five fields needed to walk into the room.
-- ==================================================================

create or replace function space_access_details(p_space_id uuid)
returns table (
  address_line text,
  lat double precision,
  lng double precision,
  entry_instructions text,
  access_type access_type
)
language sql
stable
security definer
set search_path = public
as $$
  select s.address_line, s.lat, s.lng, s.entry_instructions, s.access_type
  from spaces s
  where s.id = p_space_id
    and exists (
      select 1 from bookings b
      where b.space_id = s.id
        and b.practitioner_id = auth.uid()
        and b.status in ('upcoming', 'completed')
    );
$$;

revoke all on function space_access_details(uuid) from public;
grant execute on function space_access_details(uuid) to authenticated;


-- ===================================================================
-- 0003_storage.sql
-- ===================================================================

-- Storage buckets
--
-- Three buckets, split by sensitivity rather than by feature, since that is
-- what the access policy actually depends on:
--
--   avatars        public read, one folder per user, owner-only write
--   space-media    public read (it's marketing content — photos/video of a
--                  room, never the address), host-only write on own space
--   verification-docs   private. Sublease proof, space insurance, and
--                  practitioner insurance certs. No in-app admin panel yet
--                  (the brief calls this out as deliberate, not an
--                  oversight), so review happens by staff through the
--                  Supabase dashboard with the service role — no client
--                  policy grants read access to anyone but the uploader.
--
-- Path convention: "{owner-scoped folder}/{filename}", so a single
-- storage.foldername(name) check can express "is this yours" without a
-- table join for avatars, and with one join for the space-scoped buckets.

insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', true),
  ('space-media', 'space-media', true),
  ('verification-docs', 'verification-docs', false)
on conflict (id) do nothing;

-- Same reasoning as 0002: drop this file's own policies so it can be re-run.
-- Matched by name prefix rather than by table, because storage.objects carries
-- policies for every bucket in the project and dropping all of them would take
-- out ones this file never wrote.
do $$
declare existing record;
begin
  for existing in
    select policyname from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and (
        policyname like 'avatars:%'
        or policyname like 'space-media:%'
        or policyname like 'verification-docs:%'
      )
  loop
    execute format('drop policy if exists %I on storage.objects', existing.policyname);
  end loop;
end $$;

-- ------------------------------------------------------------------
-- avatars — path: {user_id}/{filename}
-- ------------------------------------------------------------------

create policy "avatars: public read"
  on storage.objects for select
  using (bucket_id = 'avatars');

create policy "avatars: owner writes own folder"
  on storage.objects for insert
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "avatars: owner updates own folder"
  on storage.objects for update
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "avatars: owner deletes own folder"
  on storage.objects for delete
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- ------------------------------------------------------------------
-- space-media — path: {space_id}/{filename}
-- ------------------------------------------------------------------

create policy "space-media: public read"
  on storage.objects for select
  using (bucket_id = 'space-media');

create policy "space-media: host writes own space's folder"
  on storage.objects for insert
  with check (
    bucket_id = 'space-media'
    and exists (
      select 1 from spaces s
      where s.id::text = (storage.foldername(name))[1]
        and s.host_id = auth.uid()
    )
  );

create policy "space-media: host deletes own space's folder"
  on storage.objects for delete
  using (
    bucket_id = 'space-media'
    and exists (
      select 1 from spaces s
      where s.id::text = (storage.foldername(name))[1]
        and s.host_id = auth.uid()
    )
  );

-- ------------------------------------------------------------------
-- verification-docs — no public read.
-- Paths: space/{space_id}/{filename}, practitioner/{user_id}/{filename}
-- ------------------------------------------------------------------

create policy "verification-docs: host reads own space's docs"
  on storage.objects for select
  using (
    bucket_id = 'verification-docs'
    and (storage.foldername(name))[1] = 'space'
    and exists (
      select 1 from spaces s
      where s.id::text = (storage.foldername(name))[2]
        and s.host_id = auth.uid()
    )
  );

create policy "verification-docs: host writes own space's docs"
  on storage.objects for insert
  with check (
    bucket_id = 'verification-docs'
    and (storage.foldername(name))[1] = 'space'
    and exists (
      select 1 from spaces s
      where s.id::text = (storage.foldername(name))[2]
        and s.host_id = auth.uid()
    )
  );

create policy "verification-docs: practitioner reads own docs"
  on storage.objects for select
  using (
    bucket_id = 'verification-docs'
    and (storage.foldername(name))[1] = 'practitioner'
    and (storage.foldername(name))[2] = auth.uid()::text
  );

create policy "verification-docs: practitioner writes own docs"
  on storage.objects for insert
  with check (
    bucket_id = 'verification-docs'
    and (storage.foldername(name))[1] = 'practitioner'
    and (storage.foldername(name))[2] = auth.uid()::text
  );


-- ===================================================================
-- 0004_narrow_public_profiles.sql
-- ===================================================================

-- Narrow public_host_profiles to actual hosts.
--
-- As first written it selected every row in `profiles`, so a practitioner's
-- display name and avatar were world-readable to any anonymous caller — the
-- view's name claimed a restriction its body never applied.
--
-- Only someone with a live listing needs a public identity: that is the name
-- attached to a room in Discover. A practitioner has no public presence in this
-- product at all.
--
-- Note for later: a host legitimately needs to see who booked their space, and
-- that is now deliberately not served here. It belongs in a security definer
-- function scoped to "practitioners holding a booking on a space you own",
-- alongside space_access_details, rather than in a world-readable view.

create or replace view public_host_profiles as
  select p.id, p.display_name, p.avatar_path
  from profiles p
  where exists (
    select 1
    from spaces s
    where s.host_id = p.id
      and s.status = 'active'
  );

grant select on public_host_profiles to anon, authenticated;


-- ===================================================================
-- 0005_host_bookings.sql
-- ===================================================================

-- Who booked my room?
--
-- 0004 narrowed public_host_profiles to actual hosts, which was right — a
-- practitioner has no public presence in this product — but it left a real gap:
-- a host must be able to see who is coming into their space, and that name now
-- lives behind RLS they cannot cross.
--
-- The answer is not to widen the public view back out. It is a function scoped
-- to exactly the relationship that justifies the access: you may see a
-- practitioner's name because they hold a booking on a space *you own*.
--
-- Note what it returns and what it does not. host_rate_cents is the host's net,
-- and no service fee, instant fee or platform figure appears anywhere in the
-- signature. The brief is explicit that hosts see earnings, never a percentage,
-- and leaving those columns out means a careless `select *` on the client
-- cannot leak them.

create or replace function host_bookings()
returns table (
  booking_id uuid,
  space_id uuid,
  starts_at timestamptz,
  ends_at timestamptz,
  status booking_status,
  net_cents integer,
  practitioner_name text,
  practitioner_avatar_path text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    b.id,
    b.space_id,
    b.starts_at,
    b.ends_at,
    b.status,
    b.host_rate_cents,
    p.display_name,
    p.avatar_path
  from bookings b
  join spaces s on s.id = b.space_id
  join profiles p on p.id = b.practitioner_id
  where s.host_id = auth.uid()
  order by b.starts_at;
$$;

revoke all on function host_bookings() from public;
grant execute on function host_bookings() to authenticated;


-- ===================================================================
-- 0006_service_role_grants.sql
-- ===================================================================

-- Give service_role access to the tables the server actually writes.
--
-- This was missing, and the failure mode was thoroughly misleading: the secret
-- key authenticated fine — Storage answered 200 with it — while every REST call
-- came back denied. It read like a bad key. It was a missing GRANT.
--
-- The same lesson as 0002: BYPASSRLS lets a role ignore row policies, it does
-- not let it touch a table it has no privilege on. Stock Supabase hides this by
-- granting service_role everything through default privileges; with
-- auto-expose-new-tables off there are no defaults, so nothing is granted until
-- it is written down here.
--
-- Safe because the secret key never reaches a browser: src/lib/supabase/env.ts
-- throws if it is read client-side, and src/lib/stripe/client.ts and the server
-- helpers are marked server-only.
--
-- Full access rather than a narrow list, deliberately. service_role is the
-- trusted server identity that has to write a booking, its credit_ledger entry
-- and a Stripe PaymentIntent as one unit, and reconcile them from webhooks
-- afterwards. Trimming these grants would not add safety — anything holding
-- this key can already act as the platform — it would only produce a puzzling
-- 403 the next time a route needed a column nobody anticipated.

grant usage on schema public to service_role;

grant all privileges on table profiles to service_role;
grant all privileges on table spaces to service_role;
grant all privileges on table space_media to service_role;
grant all privileges on table availability to service_role;
grant all privileges on table bookings to service_role;
grant all privileges on table credit_ledger to service_role;

grant select on table spaces_public to service_role;
grant select on table public_host_profiles to service_role;
grant select on table availability_public to service_role;
grant select on table space_media_public to service_role;
grant select on table credit_balances to service_role;
grant select on table bookings_with_access_code to service_role;

grant execute on function space_access_details(uuid) to service_role;
grant execute on function host_bookings() to service_role;

-- Anything added later inherits these, so the next table does not repeat the
-- same debugging session.
alter default privileges in schema public
  grant all privileges on tables to service_role;
alter default privileges in schema public
  grant all privileges on sequences to service_role;


-- ===================================================================
-- 0007_space_details.sql
-- ===================================================================

-- Listing detail the wizard already collects but had nowhere to land:
-- amenities, a description, and the host's house rules.
--
-- `requirements` holds keys from the fixed vocabulary in src/lib/taxonomy.ts —
-- grip socks, no open flame, quiet building — rather than sentences. Keys can
-- be shown before booking, scanned at a glance and translated later; sentences
-- can only be read.
--
-- `house_rules` is the free-text overflow for the genuinely specific ("the cat
-- lives in the back room, please keep the door shut"). Deliberately secondary
-- to the structured list: anything common belongs in the vocabulary, where it
-- is visible and consistent across listings.
--
-- Both are on `spaces` and both are exposed through spaces_public, because a
-- rule discovered after paying is exactly the surprise this app refuses
-- everywhere else. They are requirements, not fine print.

alter table spaces
  add column if not exists description text not null default '',
  add column if not exists amenities text[] not null default '{}',
  add column if not exists requirements text[] not null default '{}',
  add column if not exists house_rules text not null default '';

-- Recreated rather than altered: a view does not pick up new columns on its
-- own, and Discover cannot show a rule it never selected.
create or replace view spaces_public as
  select
    id, host_id, name, category, hourly_rate_cents, capacity, access_type,
    accessible, restroom, buffer_minutes, status, created_at,
    description, amenities, requirements, house_rules
  from spaces
  where status = 'active';

grant select on spaces_public to anon, authenticated;
grant select on spaces_public to service_role;


-- ===================================================================
-- 0008_map_position.sql
-- ===================================================================

-- Where a listing sits on the illustrated browse map.
--
-- `lat`/`lng` already existed and stayed empty, because nothing geocoded an
-- address — the wizard collected a tap on a drawing. They are now filled from
-- the address the host picks, and they remain private: released only through
-- space_access_details, to someone who already holds a booking.
--
-- map_x / map_y are the separate, public question. The map on Discover is a
-- picture, not a locator, precisely because an address is private until it is
-- booked; putting real coordinates there would undo the rule the rest of the
-- schema spends its effort enforcing. So the browse position is derived from
-- the real one at an ~11 km granularity (see toBrowsePosition in src/lib/geo.ts)
-- and only that derived value is exposed.
--
-- Stored rather than computed in the view: the derivation would otherwise need
-- lat/lng in a view anon can select from, which is the leak this exists to
-- avoid.

alter table spaces
  add column if not exists map_x numeric(4,1) not null default 50,
  add column if not exists map_y numeric(4,1) not null default 50;

-- The illustration is 6..94 by 8..92 — a pin is drawn from its point upward,
-- so a value at the very edge would render half outside the frame.
do $$
begin
  alter table spaces add constraint spaces_map_position_in_frame
    check (map_x between 6 and 94 and map_y between 8 and 92);
exception
  when duplicate_object then null;
end $$;

create or replace view spaces_public as
  select
    id, host_id, name, category, hourly_rate_cents, capacity, access_type,
    accessible, restroom, buffer_minutes, status, created_at,
    description, amenities, requirements, house_rules,
    map_x, map_y
  from spaces
  where status = 'active';

grant select on spaces_public to anon, authenticated;
grant select on spaces_public to service_role;


-- ===================================================================
-- 0009_notifications.sql
-- ===================================================================

-- Transactional messages, and the queue that stops them going twice.
--
-- The problem this table exists for: sending is not transactional. A booking
-- is written to Postgres and an email is handed to Resend, and no transaction
-- spans both — the same shape as the Stripe call in booking-service.ts. So a
-- retried job, a redeployed function or a timeout that actually delivered can
-- all send the same message again, and "your session is cancelled" arriving
-- twice is not a cosmetic bug.
--
-- The fix is a unique key per (what, about what, over which channel), claimed
-- before the send. A second attempt collides and stops. Delivery is therefore
-- at-least-once rather than exactly-once — a send that succeeds and then dies
-- before it can be marked will go again — which is the right way round: a
-- duplicate door code is an annoyance, a missing one is someone locked out.
--
-- The message body is deliberately NOT stored. It is rendered from live data
-- at send time, so a retry carries current truth rather than a stale snapshot,
-- and no door code is ever copied into a second table.

alter table profiles
  -- E.164, so the country code is never ambiguous. Verified separately from
  -- being present: an unverified number is somebody's typo until proven
  -- otherwise, and texting a stranger's phone is worse than sending nothing.
  add column if not exists phone text,
  add column if not exists phone_verified_at timestamptz,
  add column if not exists notify_sms boolean not null default false;

do $$
begin
  alter table profiles add constraint profiles_phone_is_e164
    check (phone is null or phone ~ '^\+[1-9][0-9]{6,14}$');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type notification_channel as enum ('email', 'sms');
exception
  when duplicate_object then null;
end $$;

create table if not exists notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles (id) on delete cascade,
  booking_id uuid references bookings (id) on delete cascade,
  kind text not null,
  channel notification_channel not null,

  -- The whole point of the table. Built by the caller as
  -- kind:subject-id:channel, so the same message about the same booking on the
  -- same channel can be claimed exactly once.
  dedupe_key text not null unique,

  attempts integer not null default 0,
  sent_at timestamptz,
  -- Set when a provider rejects in a way that will never succeed — a malformed
  -- address, an unreachable number. Distinct from "not sent yet" so a dead
  -- message stops being retried without pretending it was delivered.
  dropped_at timestamptz,
  last_error text,
  created_at timestamptz not null default now()
);

-- The queue's only hot query: what is still owed. Partial, because a delivered
-- notification is never looked up this way and there will be far more of those.
create index if not exists notifications_pending_idx
  on notifications (created_at)
  where sent_at is null and dropped_at is null;

create index if not exists notifications_user_idx on notifications (user_id, created_at desc);

-- ------------------------------------------------------------------
-- Access
--
-- Nobody reads this table from the client. It is written and read by the
-- service role alone, from the cron job and the booking paths — a practitioner
-- has no reason to enumerate what we have sent, and a host has less.
--
-- RLS on with no policy is the deliberate outcome: the base table denies
-- everyone, and the service role bypasses RLS entirely.
-- ------------------------------------------------------------------
alter table notifications enable row level security;

grant select, insert, update on notifications to service_role;


-- ===================================================================
-- 0010_verification_before_active.sql
-- ===================================================================

-- Move the sublease-proof requirement from "every row" to "every live listing".
--
-- sublease_doc_path was not-null, which reads like the right guarantee and is
-- not enforceable in the order the work actually happens. Storage policies for
-- the verification-docs bucket ask whether the first path segment is a space
-- this host owns, so a file cannot be uploaded until the space row exists —
-- and the row could not be inserted without the path. The only ways out were
-- to store a filename that pointed at nothing, which is what the app did and
-- left every listing unreviewable, or to write a placeholder, which is a lie
-- in a column that exists to prevent one.
--
-- The invariant worth keeping is not "no row without a document". It is "no
-- listing takes bookings without proof the host may sublet". That is what this
-- says, and it says it about exactly the moment it matters.

alter table spaces alter column sublease_doc_path drop not null;

do $$
begin
  alter table spaces add constraint spaces_active_needs_sublease_proof
    check (status <> 'active' or sublease_doc_path is not null);
exception
  when duplicate_object then null;
end $$;

-- Nothing existing can violate it: status defaults to 'pending' and only staff
-- move a listing to 'active', which is the review this constraint backs up.


-- ===================================================================
-- 0011_reviews_and_safety.sql
-- ===================================================================

-- Two-sided reviews, safety escalation, and emergency contacts.
--
-- Three things that only make sense together: a way for each side to say what
-- happened, a way for the bad ones to reach a person, and a way to reach
-- somebody if a session goes wrong while it is happening.
--
-- The rules themselves live in src/lib/reviews.ts and are tested there. What is
-- here is what the database must guarantee no matter what any client believes:
-- one review per side per booking, ratings inside 1..5, and a review that
-- cannot be written by anyone who was not in the room.

do $$
begin
  create type reviewer_role as enum ('practitioner', 'host');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type escalation_priority as enum ('safety', 'urgent', 'review');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type escalation_state as enum ('open', 'acknowledged', 'resolved');
exception
  when duplicate_object then null;
end $$;

-- ------------------------------------------------------------------
-- reviews
--
-- The sub-answers are nullable because the two roles ask different questions:
-- a practitioner is asked about access and cleanliness, a host about how the
-- room was left. Splitting into two tables would duplicate every rule about
-- visibility and escalation for the sake of a few empty columns.
-- ------------------------------------------------------------------
create table if not exists reviews (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references bookings (id) on delete cascade,
  -- Denormalised from the booking so a policy can check authorship without
  -- joining, and so a review survives as evidence of who wrote it.
  author_id uuid not null references profiles (id) on delete cascade,
  subject_id uuid not null references profiles (id) on delete cascade,
  role reviewer_role not null,

  overall smallint not null check (overall between 1 and 5),
  comment text not null default '',

  -- Ticked independently of the stars. A five-star session can still end with
  -- an unlocked fire door, and tying escalation only to a low rating loses
  -- exactly those reports.
  safety_concern boolean not null default false,

  -- Practitioner answers about the space.
  access_on_time boolean,
  cleanliness smallint check (cleanliness between 1 and 5),
  accuracy smallint check (accuracy between 1 and 5),
  would_book_again boolean,

  -- Host answers about the practitioner.
  left_as_found smallint check (left_as_found between 1 and 5),
  respected_house_rules boolean,
  on_time boolean,
  would_host_again boolean,

  created_at timestamptz not null default now(),

  -- One per side per booking. This is the constraint that makes the blind
  -- period meaningful: without it, a second review could be written after
  -- reading the counterpart.
  constraint reviews_one_per_side unique (booking_id, role),

  -- Nobody reviews themselves.
  constraint reviews_two_parties check (author_id <> subject_id)
);

create index if not exists reviews_subject_idx on reviews (subject_id, created_at desc);
create index if not exists reviews_booking_idx on reviews (booking_id);

-- ------------------------------------------------------------------
-- review_escalations
--
-- A separate row rather than a flag on the review, because what staff need to
-- track is the handling, not the rating: when it was seen, by whom, what was
-- decided. Written by the server when a qualifying review arrives.
-- ------------------------------------------------------------------
create table if not exists review_escalations (
  id uuid primary key default gen_random_uuid(),
  review_id uuid not null unique references reviews (id) on delete cascade,
  priority escalation_priority not null,
  state escalation_state not null default 'open',
  note text,
  created_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  resolved_at timestamptz
);

create index if not exists review_escalations_open_idx
  on review_escalations (priority, created_at)
  where state <> 'resolved';

-- ------------------------------------------------------------------
-- Emergency contacts
--
-- Somebody to call if a session goes wrong while it is happening. Stored on
-- the profile and readable by nobody but the owner and staff — the counterpart
-- in a booking never sees it, in either direction. A practitioner alone in a
-- stranger's building and a host letting a stranger into theirs have the same
-- need and the same right to privacy about it.
-- ------------------------------------------------------------------
alter table profiles
  add column if not exists emergency_contact_name text,
  add column if not exists emergency_contact_phone text,
  add column if not exists emergency_contact_relationship text;

do $$
begin
  alter table profiles add constraint profiles_emergency_phone_is_e164
    check (emergency_contact_phone is null or emergency_contact_phone ~ '^\+[1-9][0-9]{6,14}$');
exception
  when duplicate_object then null;
end $$;

-- ------------------------------------------------------------------
-- Access
--
-- Reviews are written through a server route, never inserted from the client:
-- eligibility depends on the session having ended and on there being no
-- earlier review, and both are checks a client can be made to skip. So there
-- is no insert policy at all — the service role writes them.
--
-- Reading is the part clients do, and it is narrow: you may read a review you
-- wrote, and a review about you once it is visible. "Visible" is not a column
-- a client can be trusted to filter on, so it is computed here.
-- ------------------------------------------------------------------
alter table reviews enable row level security;
alter table review_escalations enable row level security;

-- Dropped by name and table together, so re-running this file replaces its own
-- policies rather than colliding with them.
do $$
declare existing record;
begin
  for existing in
    select policyname, tablename from pg_policies
    where schemaname = 'public' and tablename in ('reviews', 'review_escalations')
  loop
    execute format('drop policy if exists %I on public.%I', existing.policyname, existing.tablename);
  end loop;
end $$;

create policy "reviews: author reads own"
  on reviews for select
  using (author_id = auth.uid());

grant select on reviews to authenticated;
grant select, insert, update on reviews to service_role;
grant select, insert, update on review_escalations to service_role;

-- ------------------------------------------------------------------
-- public_reviews
--
-- What a listing shows. Security definer, and its safety is the column list:
-- the author's identity, the booking it came from and the safety flag are all
-- absent, so a host cannot work out which practitioner left three stars and
-- act on it.
--
-- Only released reviews appear. A review is released when its counterpart
-- exists, or when the blind period has run out — the same rule as
-- src/lib/reviews.ts, enforced here because this is the only copy a client
-- cannot bypass.
-- ------------------------------------------------------------------
/*
 * Dropped in dependency order: space_ratings reads from public_reviews, so
 * Postgres refuses to drop the second while the first exists. Re-running the
 * file is the ordinary case — apply.sql is pasted whole — and this failed on
 * every attempt after the first.
 */
drop view if exists space_ratings;
drop view if exists public_reviews;

create view public_reviews
with (security_invoker = false) as
  select
    r.id,
    r.subject_id,
    b.space_id,
    r.role,
    r.overall,
    r.comment,
    r.created_at
  from reviews r
  join bookings b on b.id = r.booking_id
  where
    exists (
      select 1 from reviews other
      where other.booking_id = r.booking_id and other.role <> r.role
    )
    or r.created_at + interval '14 days' <= now();

grant select on public_reviews to anon, authenticated;
grant select on public_reviews to service_role;

-- ------------------------------------------------------------------
-- space_ratings
--
-- The aggregate a listing card shows. Counted from released reviews only, so
-- a sealed one cannot be inferred by watching the number move.
--
-- The average is returned raw; the decision to withhold it under three
-- reviews belongs to src/lib/reviews.ts, which is where the reason for that
-- rule is written down.
-- ------------------------------------------------------------------
create view space_ratings
with (security_invoker = false) as
  select
    space_id,
    count(*)::int as review_count,
    avg(overall)::numeric(3, 2) as average_rating
  from public_reviews
  where role = 'practitioner'
  group by space_id;

grant select on space_ratings to anon, authenticated;
grant select on space_ratings to service_role;


-- ===================================================================
-- 0012_account_type.sql
-- ===================================================================

-- One account is one side of the marketplace, chosen once.
--
-- This reverses an earlier decision, so the reasoning is worth recording. The
-- brief said "you can switch anytime from the top of either screen", and the
-- schema had no role column on purpose: the same person could book a room on
-- Tuesday and let one on Wednesday.
--
-- In practice the two sides are not two moods of one person. A practitioner
-- does not acquire a leasable room by changing a setting, and a studio owner
-- browsing for somewhere to teach is a different business with different
-- paperwork, a different fee, a different payout arrangement and a different
-- insurance position. Showing both sets of controls to everyone made the app
-- ask each person to ignore half of it.
--
-- So: an account is one or the other, picked at sign-up, and not switchable
-- afterwards. Somebody who genuinely is both opens a second account, which is
-- the honest shape of "these are two businesses".

do $$
begin
  create type account_type as enum ('practitioner', 'host');
exception
  when duplicate_object then null;
end $$;

-- Nullable, because a profile row is created the moment someone signs in and
-- the choice happens on the screen after that. Null means "has not chosen
-- yet", which the app treats as the one screen it must show them.
alter table profiles add column if not exists account_type account_type;

-- ------------------------------------------------------------------
-- Making "cannot be changed" true rather than merely unoffered.
--
-- Hiding the control is not the rule; it is a description of the current UI.
-- A client holding a publishable key can PATCH any column its grant allows,
-- so without this a practitioner could make themselves a host with one
-- request — and skip the sublease proof, the legal acknowledgement and the
-- payout setup that being a host is supposed to require.
--
-- Null to a value is permitted: that is the one-time choice. Value to a
-- different value is refused. The service role is exempt so staff can fix a
-- genuine mistake, which is the difference between immutable and a trap.
-- ------------------------------------------------------------------
create or replace function profiles_account_type_is_final()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.account_type is not null
     and new.account_type is distinct from old.account_type
     and current_user <> 'service_role'
  then
    raise exception 'account_type cannot be changed once it has been chosen'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_account_type_is_final on profiles;

create trigger profiles_account_type_is_final
  before update on profiles
  for each row
  execute function profiles_account_type_is_final();

-- ------------------------------------------------------------------
-- Listing a space requires being a host.
--
-- The trigger above stops the column changing; this stops it being
-- irrelevant. Without it, an account that never chose "host" could still
-- insert into spaces and the whole split would be decoration.
--
-- The existing policy is REPLACED rather than joined by a second one. Postgres
-- ORs permissive policies together, so adding "must be a host" beside "must be
-- your own row" would have meant either one passing — a restriction that
-- restricted nothing, and one that reads correct in a diff.
-- ------------------------------------------------------------------
drop policy if exists "spaces: host inserts own rows" on spaces;
drop policy if exists "spaces: only hosts may list" on spaces;

create policy "spaces: only hosts may list"
  on spaces for insert
  with check (
    host_id = auth.uid()
    and exists (
      select 1 from profiles p
      where p.id = auth.uid() and p.account_type = 'host'
    )
  );


-- ===================================================================
-- 0013_account_type_change_requests.sql
-- ===================================================================

-- Asking to move to the other side of the marketplace.
--
-- 0012 made account_type unchangeable by the client and left the service role
-- able to change it, which is the difference between a rule and a trap. This
-- is the front door to that exemption: somebody who picked wrong, or whose
-- circumstances genuinely changed, asks — and a person decides.
--
-- Deliberately not self-service. Becoming a host means sublease proof, a legal
-- acknowledgement and payout setup; becoming a practitioner means insurance.
-- A switch that skipped those would let an account acquire obligations it had
-- never satisfied, which is the whole reason the column is locked.

do $$
begin
  create type account_change_state as enum ('open', 'approved', 'declined');
exception
  when duplicate_object then null;
end $$;

create table if not exists account_type_change_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles (id) on delete cascade,

  -- Recorded rather than derived, so the record still reads correctly after
  -- the change has been applied and the profile no longer says what it was.
  current_type account_type not null,
  requested_type account_type not null,

  reason text not null default '',
  state account_change_state not null default 'open',

  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_note text,

  constraint account_change_is_a_change check (current_type <> requested_type)
);

-- One open request per person. Without this, a refusal can be answered by
-- asking again immediately, and the queue becomes a way to apply pressure.
create unique index if not exists account_change_one_open_per_user
  on account_type_change_requests (user_id)
  where state = 'open';

create index if not exists account_change_open_idx
  on account_type_change_requests (created_at)
  where state = 'open';

-- ------------------------------------------------------------------
-- Access
--
-- Someone may read their own requests, so the app can show "we are looking at
-- this" rather than swallowing the ask. Writing goes through a server route —
-- the current_type on the row must be the profile's real one, and a client
-- that could set it could describe a change it is not actually making.
-- ------------------------------------------------------------------
alter table account_type_change_requests enable row level security;

do $$
declare existing record;
begin
  for existing in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'account_type_change_requests'
  loop
    execute format('drop policy if exists %I on public.account_type_change_requests', existing.policyname);
  end loop;
end $$;

create policy "account changes: read own"
  on account_type_change_requests for select
  using (user_id = auth.uid());

grant select on account_type_change_requests to authenticated;
grant select, insert, update on account_type_change_requests to service_role;


-- ===================================================================
-- 0014_standing_points.sql
-- ===================================================================

-- Points, computed from what happened rather than stored.
--
-- There is no points column anywhere, on purpose. A stored balance can drift
-- from the events that produced it — a job that ran twice, a job that never
-- ran, a manual correction nobody wrote down — and once it has drifted there is
-- no way to settle an argument about it. This view recomputes from bookings and
-- reviews every time, so the number is always explainable: every point traces
-- to a session or a review somebody can be shown.
--
-- The scoring itself lives in src/lib/standing-points.ts and is tested there.
-- The constants are repeated here because SQL cannot import them, which is a
-- real duplication — standing_points.test.ts asserts they still agree.

drop view if exists standing_points;

create view standing_points
with (security_invoker = false) as
with
  -- A session counts only when money moved between two different people.
  -- Without the practitioner_id <> host_id check, a host with a second account
  -- books their own room and both sides collect, having paid only our fee.
  paid_sessions as (
    select
      b.practitioner_id,
      s.host_id,
      b.id as booking_id
    from bookings b
    join spaces s on s.id = b.space_id
    where b.status = 'completed'
      and b.captured_at is not null
      and b.practitioner_id <> s.host_id
  ),

  session_points as (
    select practitioner_id as user_id, count(*) * 15 as points from paid_sessions group by practitioner_id
    union all
    select host_id as user_id, count(*) * 15 as points from paid_sessions group by host_id
  ),

  -- Clean means nothing was raised against them on that session.
  clean_points as (
    select p.practitioner_id as user_id, count(*) * 2 as points
    from paid_sessions p
    where not exists (
      select 1 from reviews r
      where r.booking_id = p.booking_id and r.subject_id = p.practitioner_id and r.safety_concern
    )
    group by p.practitioner_id
    union all
    select p.host_id as user_id, count(*) * 2 as points
    from paid_sessions p
    where not exists (
      select 1 from reviews r
      where r.booking_id = p.booking_id and r.subject_id = p.host_id and r.safety_concern
    )
    group by p.host_id
  ),

  -- Stars on reviews *about* you, and only on sessions that counted — so a
  -- self-booked five stars is worth nothing either.
  review_points as (
    select r.subject_id as user_id, sum(r.overall) * 2 as points
    from reviews r
    join paid_sessions p on p.booking_id = r.booking_id
    group by r.subject_id
  ),

  -- Cancellations inside 24 hours, from whichever side did it.
  penalty_points as (
    select b.practitioner_id as user_id, count(*) * -25 as points
    from bookings b
    where b.status = 'cancelled_by_practitioner'
      and b.cancelled_at > b.starts_at - interval '24 hours'
    group by b.practitioner_id
    union all
    select s.host_id as user_id, count(*) * -25 as points
    from bookings b
    join spaces s on s.id = b.space_id
    where b.status = 'cancelled_by_host'
      and b.cancelled_at > b.starts_at - interval '24 hours'
    group by s.host_id
  ),

  -- An escalation that a person looked at and upheld. Open ones score nothing:
  -- a report is not a finding, and docking somebody before anybody has read it
  -- would make an accusation into a penalty.
  upheld_points as (
    select r.subject_id as user_id, count(*) * -100 as points
    from review_escalations e
    join reviews r on r.id = e.review_id
    where e.state = 'resolved' and e.note is not null
    group by r.subject_id
  )

select
  user_id,
  -- Floored at zero: a negative score keeps punishing after the punishment,
  -- and suspension is where repeated cancellation is actually handled.
  greatest(0, sum(points))::int as points
from (
  select * from session_points
  union all select * from clean_points
  union all select * from review_points
  union all select * from penalty_points
  union all select * from upheld_points
) all_points
group by user_id
/*
 * Your own row, and the filter is inside the view because it has to be.
 *
 * This is a security definer view, so it reads the base tables with the
 * owner's rights and no row policy applies — granting select without this
 * would hand every signed-in account everyone else's total. A points total is
 * not a vanity number: it is fifteen per paid session, so it divides straight
 * back into how many sessions somebody has had and, with a published rate,
 * roughly what they earned.
 *
 * auth.uid() is null for the service role, so staff read the base tables
 * directly rather than through here.
 */
having user_id = auth.uid();

grant select on standing_points to authenticated;


-- ===================================================================
-- 0015_messages.sql
-- ===================================================================

-- A thread per booking.
--
-- Scoped to a booking rather than to a pair of people, and that is the whole
-- privacy model. Two strangers have nothing to say to each other until one has
-- booked the other's room, and nothing to say afterwards once the record is
-- gone. A thread that outlived its booking would be a direct line between two
-- people who only ever agreed to share an hour.
--
-- Contact details are masked before the row is written, in
-- src/lib/message-redaction.ts. Both the sent text and the redacted text are
-- stored: the sender sees what they typed, everybody else sees what was sent.
-- Keeping the original matters when somebody reports harassment — the thing
-- that needs looking at is what was actually written.

create table if not exists messages (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references bookings (id) on delete cascade,
  sender_id uuid not null references profiles (id) on delete cascade,

  -- What the recipient sees.
  body text not null check (length(body) between 1 and 2000),

  /*
   * What the sender typed, when it differed.
   *
   * Null when nothing was masked, so the common case costs nothing. Readable
   * by staff alone — the point of masking is defeated if the recipient can
   * fetch the unmasked version, and the point of keeping it is defeated if
   * nobody can read it during a complaint.
   */
  original_body text,
  redacted_kinds text[] not null default '{}',

  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists messages_booking_idx on messages (booking_id, created_at);
create index if not exists messages_unread_idx
  on messages (booking_id)
  where read_at is null;

-- ------------------------------------------------------------------
-- booking_participants
--
-- "Are you one of the two people on this booking" is asked by every policy
-- below, and getting it slightly different in each one is how the third
-- version ends up wrong. One function, one answer.
--
-- Definer, because a practitioner has no row policy on spaces and therefore
-- cannot see who hosts the room they booked.
-- ------------------------------------------------------------------
create or replace function is_booking_participant(p_booking_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from bookings b
    join spaces s on s.id = b.space_id
    where b.id = p_booking_id
      and (b.practitioner_id = auth.uid() or s.host_id = auth.uid())
  );
$$;

-- ------------------------------------------------------------------
-- Access
--
-- Reading and writing are both allowed directly, unlike reviews. There is no
-- eligibility rule a client could skip: either you are on the booking or you
-- are not, and the function above settles it. What a client cannot be trusted
-- with is the masking, so inserts go through a server route that does it —
-- but the policy is the boundary, not the route.
-- ------------------------------------------------------------------
alter table messages enable row level security;

do $$
declare existing record;
begin
  for existing in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'messages'
  loop
    execute format('drop policy if exists %I on public.messages', existing.policyname);
  end loop;
end $$;

create policy "messages: participants read the thread"
  on messages for select
  using (is_booking_participant(booking_id));

-- Marking as read is the only update a participant makes, and only on
-- somebody else's message — you do not mark your own as read.
create policy "messages: participants mark others' as read"
  on messages for update
  using (is_booking_participant(booking_id) and sender_id <> auth.uid())
  with check (is_booking_participant(booking_id) and sender_id <> auth.uid());

grant select, update on messages to authenticated;
grant select, insert, update on messages to service_role;

-- ------------------------------------------------------------------
-- messages_visible
--
-- What a participant reads. The column list is the point: original_body is
-- absent, so the unmasked text cannot be selected by the person the masking
-- was protecting somebody from.
--
-- Invoker, so the policy above still applies — this is a narrowing of rows the
-- caller may already reach, not a way around them.
-- ------------------------------------------------------------------
drop view if exists messages_visible;

create view messages_visible
with (security_invoker = true) as
  select
    id,
    booking_id,
    sender_id,
    body,
    redacted_kinds,
    created_at,
    read_at
  from messages;

grant select on messages_visible to authenticated;
grant select on messages_visible to service_role;


-- ===================================================================
-- 0016_session_counts.sql
-- ===================================================================

-- Sessions run, replacing the points view.
--
-- 0014 built `standing_points`: a weighted score over sessions, reviews and
-- cancellations, feeding tiers that granted a longer booking window, a waived
-- instant fee and a faster payout. All of it is gone, and the reasoning is
-- worth keeping rather than only the result.
--
-- Every one of those benefits was a rule that had to be explained, tested and
-- reasoned about at the moment somebody was trying to book a room — and none of
-- them made the marketplace work better. What replaces them is a count and
-- three badges at 100, 250 and 500. A badge changes no price and bends no rule,
-- so there is nothing to reconcile when it is wrong.
--
-- The one property carried over is the one that mattered: a session counts only
-- when money moved between two different people. Without it a host books their
-- own room, and a badge that can be manufactured in an afternoon is worth
-- nothing to somebody who spent a year earning one.

drop view if exists standing_points;
drop view if exists session_counts;

create view session_counts
with (security_invoker = false) as
with paid_sessions as (
  select b.practitioner_id, s.host_id
  from bookings b
  join spaces s on s.id = b.space_id
  where b.status = 'completed'
    and b.captured_at is not null
    and b.practitioner_id <> s.host_id
)
select user_id, count(*)::int as sessions
from (
  select practitioner_id as user_id from paid_sessions
  union all
  select host_id as user_id from paid_sessions
) both_sides
group by user_id
/*
 * Your own row, and the filter has to live inside the view.
 *
 * Security definer, so it reads the base tables with the owner's rights and no
 * row policy applies — granting select without this would hand every signed-in
 * account everyone else's session count, which for a host divides straight back
 * into roughly what they have earned.
 *
 * auth.uid() is null for the service role, so staff read the base tables
 * directly rather than through here.
 */
having user_id = auth.uid();

grant select on session_counts to authenticated;
